/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    'dusk.login': [
      {
        name: 'userId'
        required: true
      },
      {
        name: 'guard'
        required: false
      }
    ]
    'dusk.logout': [
      {
        name: 'guard'
        required: false
      }
    ]
    'dusk.user': [
      {
        name: 'guard'
        required: false
      }
    ]
    telescope: [
      {
        name: 'view'
        required: false
      }
    ]
    home: []
    dashboard: []
    'projects.index': []
    'projects.show': [
      {
        name: 'id'
        required: true
      }
    ]
    'projects.store': []
    'projects.destroy': [
      {
        name: 'id'
        required: true
      }
    ]
    'profile.edit': []
    'profile.update': []
    'profile.destroy': []
    'password.edit': []
    'password.update': []
    appearance: []
    'language.edit': []
    'language.update': []
    register: []
    login: []
    'password.request': []
    'password.email': []
    'password.reset': [
      {
        name: 'token'
        required: true
      }
    ]
    'password.store': []
    'verification.notice': []
    'verification.verify': [
      {
        name: 'id'
        required: true
      },
      {
        name: 'hash'
        required: true
      }
    ]
    'verification.send': []
    'password.confirm': []
    logout: []
    'storage.local': [
      {
        name: 'path'
        required: true
      }
    ]
  }
}
export {}
