name: tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: write

env:
  HUSKY: 0

jobs:
  tests:
    runs-on: ubuntu-latest

    container:
      # https://playwright.dev/docs/docker#pull-the-image
      image: mcr.microsoft.com/playwright:v1.52.0-noble

    name: Tests

    steps:
      # @NOTE playwright image has a discrepancy between the current user and the owner of the project folder
      # which prevents git commits due to "detected dubious ownership"
      - name: Fix Playwright
        run: chown root:root .

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: json, dom, curl, libxml, mbstring
          coverage: xdebug

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --optimize-autoloader
          pnpm install

      - name: Build Assets
        run: pnpm run build

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Run PHP Tests
        run: php artisan test --coverage

      - name: Run TS Tests
        run: pnpm run test

      - name: Update PHP Coverage Badge
        run: bin/php-coverage

      - name: Update TS Coverage Badge
        run: bin/ts-coverage

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update coverage badges"
          commit_options: '--no-verify'
